VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes

QMK_SETTINGS = no
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
CAP_WORD_ENABLE = yes


# Size optimization
LADDER_ENABLE = no
MOUSEKEY_ENABLE = no
#COSOLE_ENABLE = no
#COMMAND_ENABLE = no
LTO_ENABLE = yes
KEY_LOCK_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
